# Generated by Django 4.1.7 on 2023-03-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('color', models.IntegerField(choices=[(1, 'White'), (2, 'Black'), (4, 'Red'), (8, 'Blue')])),
                ('number', models.CharField(max_length=15)),
                ('type', models.IntegerField(choices=[(1, 'Sedan'), (2, 'Hatchback'), (4, 'Truck'), (8, 'Coupe')])),
            ],
        ),
    ]
